name: no_poverty
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.4.2
  path: ^1.9.1
  shared_preferences: ^2.5.3
  animated_toggle_switch: ^0.8.5
  flutter_markdown: ^0.7.7+1
  http: ^1.5.0
  provider: ^6.1.5+1
  cupertino_icons: ^1.0.8
  intl: ^0.20.2
  sqflite_common_ffi: ^2.3.3
  geolocator: ^14.0.2
  geocoding: ^4.0.0
  firebase_core: ^3.8.0
  firebase_auth: ^5.3.1
  google_sign_in: ^6.2.1
  firebase_analytics: ^11.6.0
  cloud_firestore: ^5.6.12
  image_picker: ^1.1.2         
  permission_handler: ^11.3.1   
  supabase_flutter: ^2.10.3
  awesome_notifications: ^0.10.1
  google_mobile_ads: ^7.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
